"""empty message

Revision ID: 87df6dd81451
Revises: 79d76169da18
Create Date: 2026-04-06 13:07:38.532341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87df6dd81451'
down_revision: Union[str, Sequence[str], None] = '79d76169da18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('gdd_file_key', sa.Text(), nullable=True))
    op.drop_column('projects', 'gdd_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('gdd_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'gdd_file_key')
    # ### end Alembic commands ###
